language: php
php:
  - 5.5
  - 5.6
  - hhvm
services:
  - riak

before_script:
  - composer self-update
  - composer update

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
